use_frameworks!

target 'QuickGWT_Example' do
  pod 'QuickGWT', :path => '../'
  pod 'InjectableLoggers'
  
  target 'QuickGWT_Tests' do
    inherit! :search_paths
    pod 'Nimble'
    pod 'MockNStub'
  end
end
